### ISSUE TITLE
ros-jazzy-desktop* contain libamdhip64.so.5 with executable stack

### ISSUE THREAD

**Issue by Guillaumebeuzeboc** [canonical/ros-content-sharing-snaps#15]
From the automatic Snap Store review:
```
 “Found files with executable stack. This adds PROT_EXEC to mmap(2) during mediation which may cause security denials. Either adjust your program to not require an executable stack, strip it with 'execstack --clear-execstack ...' or remove the affected file from your snap. Affected files: usr/lib/x86_64-linux-gnu/libamdhip64.so.5.7.31921 functional-snap-v2_execstack
```
Notes from the manual reviewer:
```
Approving for now, but please update your snap so it will pass automated review. For an example of how to fix this see https://github.com/alexmurray/amberol-snap/commit/20bc35f29a90c12f177c55de740cfc7fd77a6629”
```

The library `libamdhip64.so.5` from the package `libamdhip64-5` contains an executable stack that doesn't pass the Snap Store automatic review.
The package libamdhip64-5 is a dependency from the `libpcl-dev` used in packages like `ros-jazzy-cartographer-ros` or even `ros-jazzy-velodyne-pointcloud`

The dependency tree is `libamdhip64-5` -> `libucx0` ->`libopenmpi3t64` ->`libopenmpi-dev` ->`mpi-default-dev` -> `libvtk9-dev` ->`libvtk9-qt-dev` -> `libpcl-dev`

The library `libamdhip64.so.5` is not supposed to have the exec stack. It was [enabled by default by mistake](https://github.com/ROCm/clr/issues/22).
The issue [got fixed in the next major version (6)](https://github.com/ROCm/clr/commit/14cbd8d24cfcff724b82f78413e1c1440f356d4e)

As a temporary solution we can manually remove the exec stack from the library.

**Comment by Guillaumebeuzeboc** [comment]
A MR got merged on review-tools so this library gets ignored: https://code.launchpad.net/~gbeuzeboc/review-tools/+git/review-tools/+merge/469447

**Comment by Guillaumebeuzeboc** [comment]
The change of `review-tool` is now available on `latest/stable`. Should we revert back the change we made here? @artivis

**Comment by MirkoFerrati** [comment]
> The change of `review-tool` is now available on `latest/stable`. Should we revert back the change we made here? @artivis

Fine for me!

**Comment by Guillaumebeuzeboc** [comment]
https://github.com/canonical/ros2-nav2-snap/pull/20
